### ISSUE TITLE
coordinator cpu contention when running 1m aggregation of samples

### ISSUE THREAD

**Issue by BertHartm** [m3db/m3#1112]
I'm running coordinator on a dedicated 32 core box and running about 90k samples/s through it (after replication, with RF=3). I'm using 0.4.6, have 1 prometheus, and 6 db instances.
It generally uses 3 about 3 cores, and I've got it sending to an unaggregated namespace and a namespace aggregating at the 1h level.
Here's what the baseline looks like 
[m3coordinator.only_hourly.pb.gz](https://github.com/m3db/m3/files/2492682/m3coordinator.only_hourly.pb.gz)

I turned on a 1m aggregation namespace, and cpu usage jumped to 28 cores, mostly in system time. 
here's my cpu graph for the box:
![image](https://user-images.githubusercontent.com/508811/47168343-a5b50500-d2ce-11e8-9cc8-4dbc5bec6c47.png)
and here are 3 profiles grabbed in that window, 2 for 15s, and one for 60s:
[m3coordinator.slow_15s_1.pb.gz](https://github.com/m3db/m3/files/2492695/m3coordinator.slow_15s_1.pb.gz)
[m3coordinator.slow_15s_2.pb.gz](https://github.com/m3db/m3/files/2492699/m3coordinator.slow_15s_2.pb.gz)
[m3coordinator.slow_60s.pb.gz](https://github.com/m3db/m3/files/2492678/m3coordinator.slow_60s.pb.gz)

When I disabled the 1m aggregation level and restarted the coordinator (15:37 in the graph), system time was still high, but recovered.
Here's a profile about 5m after the restart: 
[m3coordinator.in_recovery.pb.gz](https://github.com/m3db/m3/files/2492703/m3coordinator.in_recovery.pb.gz)

let me know what else I can provide.
Thanks,
Bert

**Comment by prateek** [comment]
Didn't mean to close this issue. We're still investigating heap usage increase.

**Comment by BertHartm** [comment]
Here's a heap of master (`2bd8e43f`) running with the 10m downsampling after a few minutes.

[coordinator_heap.out.gz](https://github.com/m3db/m3/files/2497310/coordinator_heap.out.gz)

**Comment by BertHartm** [comment]
here's another a few minutes later after it's semi-plateaued and had a chance to send out some metrics (at least, I see a big network spike that seems like it should correspond)

[coordinator_heap.out.gz](https://github.com/m3db/m3/files/2497336/coordinator_heap.out.gz)

**Comment by BertHartm** [comment]
I ran another experiment today, and running the additional namespace at 60m resolution is also causing the memory issue.

here's the relevant sample of my coordinator config:
```
clusters:
  - namespaces:
      - namespace: metrics15d
        retention: 360h
        storageMetricsType: unaggregated
      - namespace: metrics9w
        retention: 1512h
        storageMetricsType: aggregated
        resolution: 60m
      - namespace: metrics18m
        retention: 13152h
        storageMetricsType: aggregated
        resolution: 60m
```

My intention is to move the 2nd of those namespaces to 1m resolution, so that was the one I commented out when things got unstable. It turns out that I can comment out either and it runs fine, but having both aggregated namespaces enabled causes this memory issue.

I'm going to try running my `metrics9w` namespace at 10m and 1m and see what the performance impact is.
