### ISSUE TITLE
Dynamically generate new metric name in rollup rule

### ISSUE THREAD

**Issue by cw9** [m3db/m3#1171]
Currently when defining rollup rules, we require user to provide a new name for the new roll up metric `statically`. We do this because we want to make sure we don't double count the value from both the raw metrics and rollup metrics into a potential query like `fetch name:cpu_load | sum` that could match both.

For example:
```
  - name: average cpu load
    filter: name:cpu_load host:*
    targets:
      - pipeline:
        - rollup:
            newName: cpu_load_avg
            aggregation:
              - Mean
```
This rule calculates the average of `cpu_load` from all hosts and generate a new metric with name `cpu_load_avg`.

With this design, when users want to calculate the average on `cpu`, `memory`, `network_in`, `network_out`..., they would have to define one rule per metric name because they need to statically put in the `newName` in the rollup rule.

It would be great if we could dynamically generate the new metric name based on the original metric name, which could look like:

 ```
  - name: average all server usage metrics
    filter: host:* server_usage_metric:v1
    targets:
      - pipeline:
        - rollup:
            newName: %name% + "_avg" 
            aggregation:
              - Mean
```

This could then be applied to all metrics that satisfy the filter and save users the trouble to repeat the similar rule per metric name.
