### ISSUE TITLE
stuck in initializing state for long retention periods

### ISSUE THREAD

**Issue by arnaud-mey** [m3db/m3#1577]
Hi there,
all shards are stuck in the initializing state. We suspect that this behavior is caused by a long retention time (~13 months) since it doesn't appear for short retention times.
We are using m3dbnode v0.8.0 with m3operator v0.1.4.
We are seeing the following log entries on all nodes:
```
11:07:36.413636[E] error when flushing data for time 2019-04-20 11:07:26.410666894 +0000 UTC m=+156095.694151320: persist manager cannot start persist, not idle

11:07:37.377660[D] not bootstrapped and durable because: no last snapshot start time [{lastBootstrapCompletionTime 2019-04-18 15:47:44.90400145 +0000 UTC m=+114.187485904} {lastSnapshotStartTime 0001-01-01 00:00:00 +0000 UTC}]
```
Our namespace config:
```
spec:
  numberOfShards: 256
  replicationFactor: 3
  namespaces:
  - name: default
    options:
      bootstrapEnabled: true
      flushEnabled: true
      writesToCommitLog: true
      cleanupEnabled: true
      repairEnabled: false
      snapshotEnabled: true
      retentionOptions:
        retentionPeriod: "9516h" 
        blockSize: "2h"
        bufferFuture: "10m"
        bufferPast: "10m"
        blockDataExpiry: true
        blockDataExpiryAfterNotAccessPeriod: "5m"
      indexOptions:
        enabled: true
        blockSize: "4h"

```
