### ISSUE TITLE
Additional m3query remotes configuration

### ISSUE THREAD

**Issue by pavelnikolov** [m3db/m3#1921]
# Additional m3query RPC remotes configuration

## Overview
This is a feature request to allow for configuring additional RPC remotes for m3query. The current way m3query is configured is sub-optimal in some cases.

## The problem
In our use-case we have many Kubernetes clusters. In each cluster we have m3db and m3query in front of it. A cluster can appear/disappear at any time. Therefore, I need to configure some kind of service discovery mechanism so that each of the m3queries instances can fan-out queries to each of the other m3query instances.

## Suggested solution
Ideally, I imagine this as a separate file that the app can read from. In my mind it should be similar to the [additional scrape config](https://github.com/coreos/prometheus-operator/blob/master/Documentation/additional-scrape-config.md#additional-scrape-configuration) that the Prometheus operator supports.
This in turn would allow me to store this config in a Kubernetes secret and mount this file to the m3query pod. Then, each time a new cluster registers with the service discovery would result in the secret being updated in each of the other clusters. This in turn will reconfigure each of m3query instances in the remaining clusters to use the new m3query instance as a RPC remote target.

## Merge of remotes
If the m3query config already contains RPC remotes, then I imagine that the additional RPC remotes will be merged at app start time.

**Comment by martin-mao** [comment]
@robskillington @arnikola @schallert @benraskin92 FYI

**Comment by pavelnikolov** [comment]
I have another idea... 💭 
I noticed that in your code in addition to `xconfig.LoadFile` you also support `xconfig.LoadFiles` to load code from multiple config files:

```go
// LoadFiles loads a config from list of files. If value for a property is
// present in multiple files, the value from the last file will be applied.
// Validation is done after merging all values.
func LoadFiles(config interface{}, files []string, opts Options) error {
   ...
}
```

What if you allow for multiple config files? 🤔 
For example I could do this:

```
$ ./m3query -f config.yaml -f remotes.yaml
``` 
Where my `config.yaml` contains the normal config and `remotes.yaml` looks like this:

```yaml
  rpc:
    remotes:
      - name: "cluster-1"
        remoteListenAddresses: ["cluster-1.m3.example.com:7202"]
      - name: "cluster-2"
        remoteListenAddresses: ["cluster-2.m3.example.com:7202"]
      - name: "cluster-n"
        remoteListenAddresses: ["cluster-n.m3.example.com:7202"]
```

This would allow me to store the second file in a Kubernetes secret and then every time this secret gets updated my m3query pod will get restarted. Also, the application that updates the remotes will never have to deal with the rest of the config (less chances of facing breaking changes in future).
