### ISSUE TITLE
Memory leak introduced by cold flush

### ISSUE THREAD

**Issue by Betula-L** [m3db/m3#2015]
## Performance issues

1. What service is experiencing the performance issue? (M3Coordinator, M3DB, M3Aggregator, etc)
    M3DB

2. Approximately how many datapoints per second is the service handling?
    2889767 per minitue

3. What is the hardware configuration (number CPU cores, amount of RAM, disk size and types, etc) that the service is running on? Is the service the only process running on the host or is it colocated with other software?
     40 core, 128G memory. m3db used about 100G memory.

5. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).
```
  client:
    writeConsistencyLevel: majority
    readConsistencyLevel: unstrict_majority

  gcPercentage: 100

  writeNewSeriesAsync: true
  writeNewSeriesLimitPerSecond: 1048576
  writeNewSeriesBackoffDuration: 2ms

  bootstrap:
    # Intentionally disable peers bootstrapper to ensure it doesn't interfere with test.
    bootstrappers:
      - filesystem
      - commitlog
      - peers
      - uninitialized_topology
```
```
curl -X POST localhost:7201/api/v1/namespace -d '{
  "name": "prometheus-remote-storage",
  "options": {
    "bootstrapEnabled": true,
    "flushEnabled": true,
    "writesToCommitLog": true,
    "cleanupEnabled": true,
    "snapshotEnabled": true,
    "repairEnabled": false,
    "retentionOptions": {
      "retentionPeriodDuration": "48h",
      "blockSizeDuration": "2h",
      "bufferFutureDuration": "30m",
      "bufferPastDuration": "60m",
      "blockDataExpiry": true,
      "blockDataExpiryAfterNotAccessPeriodDuration": "5m"
    },
    "coldWritesEnabled": false,
    "indexOptions": {
      "enabled": true,
      "blockSizeDuration": "2h"
    }
  }
}'
```
### What should be it?

I observed m3db memory usage for last 4 days, and it always increased slow, finally my machine was OOM. Whereas, retentionPeriodDuration is only 48h.

I tried to root cause where memory leaks, and found something interesting.

PR https://github.com/m3db/m3/pull/1624 is implemented to support cold flushes, since that series should be saved more time for cold flush function `Merge`. 

commit https://github.com/m3db/m3/pull/1624/commits/a1153313a75297433e879df08c39e8df5d2fc78f set tags NoFinalize, so series will not be gc immediately whether coldFlush is enabled or not.
https://github.com/m3db/m3/blob/a1153313a75297433e879df08c39e8df5d2fc78f/src/dbnode/storage/shard.go#L1100

If `coldFlush` was enabled, tags will be Finalize() in function `Merge` eventually which is triggered by function `ColdFlush`, but if `coldFlush` was disabled, only function `WarmFlush` will be triggered. Thus, series will not be set Finalize() if `coldFlush` was disabled.
https://github.com/m3db/m3/blob/0c23eb64e8891ce4c84607c247867a442a297a3a/src/dbnode/persist/fs/merger.go#L186

To validate the below conclusion,  i annotated this line, since i do not need save series if `coldFlush` was disabled, and run the hot-fix version about 6h. There is no significant memory increment anymore.

### Heap Profiles

**Comparison at the same load:**
Memory usage on m3dbnode v1.14.1:
![image](https://user-images.githubusercontent.com/6059935/67557452-b1d86b80-f747-11e9-869f-e8043dc24109.png)

Memory usage  if annotated NoFinalize:
https://github.com/m3db/m3/blob/a1153313a75297433e879df08c39e8df5d2fc78f/src/dbnode/storage/shard.go#L1100
![image](https://user-images.githubusercontent.com/6059935/67569282-0b00c900-f761-11e9-9307-9aaf9e23ad10.png)

The following files include heap dump for last 4day.
[run-50m.zip](https://github.com/m3db/m3/files/3771237/run-50m.zip)
[run-6h.zip](https://github.com/m3db/m3/files/3771246/run-6h.zip)
[run-4d.zip](https://github.com/m3db/m3/files/3771247/run-4d.zip)
[run-1d.zip](https://github.com/m3db/m3/files/3771243/run-1d.zip)

![image](https://user-images.githubusercontent.com/6059935/67278439-924d0300-f4fb-11e9-9d7a-6a505a42aab2.png)
