### ISSUE TITLE
query instant metrics from m3db failed every 8 hours,and then recover automatically after about 30 minutes to one hour

### ISSUE THREAD

**Issue by victzhao** [m3db/m3#2028]
We use m3db to store data. Prometheus queries data from m3db through m3coordinator (both Prometheus and m3coordinator are installed on the same machine). Prometheus sets some alert rules and serves as data source of grafana. We found a phenomenon that the CPU utilization rate of Prometheus for query would fluctuate slightly every two hours, and fluctuate greatly every eight hours. When we query the Instant metrics on grafana, we can't find the data occasionally at 00:00, 08:00 and 16:00 every day, and recover automatically after about 30 minutes to one hour. No error in m3db and m3coordinator。

### 5. two namespaces:

```
curl -X POST http://127.0.0.1:7201/api/v1/namespace -d '{
  "name": "default",
  "options": {
    "bootstrapEnabled": true,
    "flushEnabled": true,
    "writesToCommitLog": true,
    "cleanupEnabled": true,
    "snapshotEnabled": true,
    "repairEnabled": false,
    "retentionOptions": {
      "retentionPeriodDuration": "48h",
      "blockSizeDuration": "2h",
      "bufferFutureDuration": "20m",
      "bufferPastDuration": "20m",
      "blockDataExpiry": true,
      "blockDataExpiryAfterNotAccessPeriodDuration": "10m"
    },
    "indexOptions": {
      "enabled": true,
      "blockSizeDuration": "8h"
    }
  }
}'

curl -X POST localhost:7201/api/v1/namespace -d '{
  "name": "metrics",
  "options": {
    "bootstrapEnabled": true,
    "flushEnabled": true,
    "writesToCommitLog": true,
    "cleanupEnabled": true,
    "snapshotEnabled": true,
    "repairEnabled": false,
    "retentionOptions": {
      "retentionPeriodDuration": "720h",
      "blockSizeDuration": "12h",
      "bufferFutureDuration": "1h",
      "bufferPastDuration": "1h",
      "blockDataExpiry": true,
      "blockDataExpiryAfterNotAccessPeriodDuration": "5m"
    },
    "indexOptions": {
      "enabled": true,
      "blockSizeDuration": "12h"
    }
  }
}'
````
### 6. m3coordinator.yaml
```

listenAddress:
  type: "config"
  value: "0.0.0.0:7201"

metrics:
  scope:
    prefix: "coordinator"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
  sanitization: prometheus
  samplingRate: 1.0
  extended: none

tagOptions:
  idScheme: quoted

clusters:
  - namespaces:
      - namespace: default
        retention: 48h
        type: unaggregated
      - namespace: metrics
        type: aggregated
        retention: 720h
        resolution: 5m
    client:
      config:
        service:
          env: default_env
          zone: embedded
          service: m3db
          cacheDir: /var/lib/m3kv
          etcdClusters:
            - zone: embedded
              endpoints:
                - etcd01:2379
                - etcd02:2379
                - etcd03:2379
      writeConsistencyLevel: majority
      readConsistencyLevel: unstrict_majority
```

### 7. Prometheus cpu trends on 00:00 08:00 16:00 every day

![prometheus](https://user-images.githubusercontent.com/15981202/67850777-0a42ab00-fb44-11e9-98c2-d9b75cbf2430.png)

### 8. grafana on 00:00 08:00 16:00 every day.

![disk](https://user-images.githubusercontent.com/15981202/67850867-36f6c280-fb44-11e9-974b-2b0dc11ecb16.png)
