### ISSUE TITLE
Roullup is not in effect

### ISSUE THREAD

**Issue by wang1219** [m3db/m3#2179]
# 1. I configured the rollup using the v0.15.0 M3Coordinator, but it did not work
### config
```
listenAddress:
  type: "config"
  value: "0.0.0.0:7201"


metrics:
  scope:
    prefix: "coordinator"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
  sanitization: prometheus
  samplingRate: 1.0
  extended: none

tagOptions:
    # Configuration setting for generating metric IDs from tags.
    idScheme: legacy

clusters:
   - namespaces:
# We created a namespace called "default" and had set it to retention "48h".
       - namespace: default
         retention: 12h
         type: unaggregated
       - namespace: metrics_300s_48h
         type: aggregated
         retention: 48h
         resolution: 300s
         downsample:
           all: false
     client:
       config:
         service:
           env: default_env
           zone: embedded
           service: m3db
           cacheDir: /var/lib/m3kv
           etcdClusters:
             - zone: embedded
               endpoints:
# We have five M3DB nodes but only three are seed nodes, they are listed here.
                 - 127.0.0.1:2379
       writeConsistencyLevel: majority
       readConsistencyLevel: unstrict_majority
       writeTimeout: 10s
       fetchTimeout: 15s
       connectTimeout: 20s
       writeRetry:
         initialBackoff: 500ms
         backoffFactor: 3
         maxRetries: 2
         jitter: true
       fetchRetry:
         initialBackoff: 500ms
         backoffFactor: 2
         maxRetries: 3
         jitter: true
       backgroundHealthCheckFailLimit: 4
       backgroundHealthCheckFailThrottleFactor: 0.5


downsample:
  rules:
    rollupRules:
      - name: "commitlog_writes_success avg by job"
        filter: "__name__:commitlog_writes_success job:*"
        transforms:
          - transform:
              type: "PerSecond"
          - rollup:
              metricName: "commitlog_writes_success_avg"
              groupBy: ["job"]
              aggregations: ["Mean", "Last", "Min", "Max", "Median", "Count", "Sum", "SumSq", "Stdev", "P10", "P30", "P50", "P70", "P90", "P95", "P99", "P999"]
        storagePolicies:
          - resolution: 300s
            retention: 48h
      - name: "node_filesystem_avail_bytes by instance mountpoint"
        filter: "__name__:node_filesystem_avail_bytes mountpoint:* instance:*"
        transforms:
          - transform:
              type: "PerSecond"
          - rollup:
              metricName: "node_filesystem_avail_bytes_by_instance"
              groupBy: ["instance", "mountpoint"]
              aggregations: ["Mean", "Last", "Min", "Max", "P99"]
        storagePolicies:
          - resolution: 300s
            retention: 48h
      - name: "node_filesystem_size_bytes by instance mountpoint"
        filter: "__name__:node_filesystem_size_bytes mountpoint:* instance:*"
        transforms:
          - transform:
              type: "Absolute"
          - rollup:
              metricName: "node_filesystem_size_bytes_by_instance"
              groupBy: ["mountpoint", "instance"]
              aggregations: ["Mean", "P99"]
        storagePolicies:
          - resolution: 300s
            retention: 48h

    # NB(r): Use high buffer past limits for test since we are using
    #   # resolution of 5s which races against the timestamps being ingested.
  bufferPastLimits:
    - resolution: 0s
      bufferPast: 90s
```

Not found new Metrics `commitlog_writes_success_avg`, `node_filesystem_avail_bytes_by_instance`, `node_filesystem_size_bytes_by_instance`

![image](https://user-images.githubusercontent.com/18459440/75421686-c9359880-5975-11ea-9b00-6579bfe167a3.png)
![image](https://user-images.githubusercontent.com/18459440/75421704-cfc41000-5975-11ea-909d-d58dabf0e862.png)

# 2. Also, there was an error when I created a new rollup using the m3ctl UI
### UI request
![image](https://user-images.githubusercontent.com/18459440/75422454-955b7280-5977-11ea-9765-0b815908d78a.png)

But /r2/v1/namespaces/{namespaceID}/rollup-rules should accept parameters like this
```
{
    "name": "test",
    "filter": "__name__:node_filesystem_size_bytes mountpoint:* instance:* type:timer",
    "targets": [
      {
        "pipeline": [
          {
            "rollup": {
              "newName": "node_filesystem_size_bytes_by_instance",
              "aggregation": [
                "Mean"
              ]
            }
          }
        ],
        "storagePolicies": [{"retention": "48h","resolution":"300s"}]
      }
    ]
 }
```
But there are still errors
```
{
"code": 400,
"message": "Malformed Json: json: cannot unmarshal object into Go struct field RollupTarget.storagePolicies of type policy.StoragePolicy"
}
```
This is because different type between RollupTarget.storagePolicies and policy.StoragePolicy.

**I want to use rollup, please help, thank you.**
