### ISSUE TITLE
v15.0 m3coordinator cpu high

### ISSUE THREAD

**Issue by ning1875** [m3db/m3#2389]
![image](https://user-images.githubusercontent.com/20356568/83752328-f394a180-a69a-11ea-81d1-dd67ce11365a.png)
after upgrade m3coordinator  to v15.0 ,it cpu useage grow high 
here is my m3coordinator.yaml and it is used for promethues remote_read only
```
listenAddress:
  type: "config"
  value: "0.0.0.0:7201"

metrics:
  scope:
    prefix: "coordinator"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
  sanitization: prometheus
  samplingRate: 1.0
  extended: none
limits:
  perQuery:
    maxFetchedSeries: 10000000
    maxComputedDatapoints: 10000000
    maxFetchedDatapoints: 10000000

tagOptions:
  idScheme: quoted

clusters:
# Fill-out the following and un-comment before using, and
# make sure indent by two spaces is applied.
  - namespaces:
      - namespace: default
        retention: 360h
        type: unaggregated
    client:
      config:
        service:
          env: default_env
          zone: embedded
          service: m3db
          cacheDir: /var/lib/m3kv
          etcdClusters:
            - zone: embedded
              endpoints:
                -xxx:2379
                - xxx:2379
                - xxx:2379
#                ... etc, list only M3DB seed nodes
      writeConsistencyLevel: majority
      #readConsistencyLevel: unstrict_majority
      readConsistencyLevel: one

```
