### ISSUE TITLE
A connection problem between m3coordinator and m3aggregator

### ISSUE THREAD

**Issue by xcode03** [m3db/m3#2392]
# Filing M3 Issues

## General Issues

General issues are any non-performance related issues (data integrity, ease of use, error messages, configuration, documentation, etc).

Please provide the following information along with a description of the issue that you're experiencing:

1. What service is experiencing the issue? (M3Coordinator, M3DB, M3Aggregator, etc)

A: M3Aggregator and M3Coordinator. 

After starting m3db to access prometheus data, the following error will be reported in the coordinator log
```
{"level":"error","ts":1591332167.2434337,"msg":"error writing data","buffer_size":5458038,"target_instance":"m3aggregator-1.m3aggregator:6000","error":"write tcp 192.168.34.175:47004->192.168.31.120:6000: i/o timeout"}
{"level":"error","ts":1591332167.343498,"msg":"error writing data","buffer_size":6168846,"target_instance":"m3aggregator-1.m3aggregator:6000","error":"no active connection"}
{"level":"error","ts":1591332167.446228,"msg":"error writing data","buffer_size":1187541,"target_instance":"m3aggregator-1.m3aggregator:6000","error":"no active connection"}
{"level":"error","ts":1591332167.5462797,"msg":"error writing data","buffer_size":1017763,"target_instance":"m3aggregator-1.m3aggregator:6000","error":"no active connection"}
{"level":"error","ts":1591332167.6465204,"msg":"error writing data","buffer_size":177915,"target_instance":"m3aggregator-1.m3aggregator:6000","error":"no active connection"}
{"level":"error","ts":1591332167.746639,"msg":"error writing data","buffer_size":592179,"target_instance":"m3aggregator-1.m3aggregator:6000","error":"no active connection"}
{"level":"error","ts":1591332167.8467834,"msg":"error writing data","buffer_size":160688,"target_instance":"m3aggregator-1.m3aggregator:6000","error":"no active connection"}
{"level":"error","ts":1591332168.0469425,"msg":"error writing data","buffer_size":277034,"target_instance":"m3aggregator-1.m3aggregator:6000","error":"no active connection"}
{"level":"error","ts":1591332168.147124,"msg":"error writing data","buffer_size":663853,"target_instance":"m3aggregator-1.m3aggregator:6000","error":"no active connection"}
{"level":"error","ts":1591332168.2472672,"msg":"error writing data","buffer_size":73801,"target_instance":"m3aggregator-1.m3aggregator:6000","error":"no active connection"}
```
The aggregator log has the following error:
```
{"level":"error","ts":1591332385.5303082,"msg":"decode error","remoteAddress":"192.168.30.229:47326","error":"unexpected EOF"}
{"level":"error","ts":1591332385.548677,"msg":"decode error","remoteAddress":"192.168.34.175:47258","error":"unexpected EOF"}
{"level":"error","ts":1591332385.8085418,"msg":"decode error","remoteAddress":"192.168.27.92:48086","error":"unexpected EOF"}
{"level":"error","ts":1591332385.9047897,"msg":"decode error","remoteAddress":"192.168.30.229:48166","error":"unexpected EOF"}
{"level":"error","ts":1591332385.978183,"msg":"decode error","remoteAddress":"192.168.34.175:47316","error":"unexpected EOF"}
{"level":"error","ts":1591332386.2282352,"msg":"decode error","remoteAddress":"192.168.27.92:48092","error":"unexpected EOF"}
{"level":"error","ts":1591332386.376796,"msg":"decode error","remoteAddress":"192.168.34.175:47390","error":"unexpected EOF"}
{"level":"error","ts":1591332386.5740309,"msg":"decode error","remoteAddress":"192.168.30.229:48780","error":"unexpected EOF"}
{"level":"error","ts":1591332390.8387365,"msg":"decode error","remoteAddress":"192.168.27.92:48152","error":"unexpected EOF"}
{"level":"error","ts":1591332390.9998877,"msg":"decode error","remoteAddress":"192.168.34.175:47414","error":"unexpected EOF"}
```
But at present, writing and querying of prometheus is normal.
May I ask what went wrong, I hope you can answer my questions, thank you.

2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).

A:
M3Aggregator.yaml
```
logging:
  level: info

metrics:
  scope:
    prefix: m3aggregator
  prometheus:
    onError: none
    handlerPath: /metrics
    listenAddress: 0.0.0.0:6002
    timerType: histogram
  sanitization: prometheus
  samplingRate: 1.0
  extended: none

http:
  listenAddress: 0.0.0.0:6001
  readTimeout: 60s
  writeTimeout: 60s

rawtcp:
  listenAddress: 0.0.0.0:6000
  keepAliveEnabled: true
  keepAlivePeriod: 1m
  retry:
    initialBackoff: 5ms
    backoffFactor: 2.0
    maxBackoff: 1s
    forever: true
    jitter: true
  readBufferSize: 1440
  msgpackIterator:
    ignoreHigherVersion: false
    readerBufferSize: 1440
    largeFloatsSize: 1024
    largeFloatsPool:
      buckets:
        - count: 1024
          capacity: 2048
        - count: 512
          capacity: 4096
        - count: 256
          capacity: 8192
        - count: 128
          capacity: 16384
        - count: 64
          capacity: 32768
        - count: 32
          capacity: 65536
      watermark:
        low: 0.001
        high: 0.002
  protobufIterator:
    initBufferSize: 1440
    maxMessageSize: 50000000  # max message size is 50MB
    bytesPool:
      buckets:
        - count: 1024
          capacity: 2048
        - count: 512
          capacity: 4096
        - count: 256
          capacity: 8192
        - count: 128
          capacity: 16384
        - count: 64
          capacity: 32768
        - count: 32
          capacity: 65536
      watermark:
        low: 0.001
        high: 0.002

kvClient:
  etcd:
    env: default_env
    zone: embedded
    service: m3aggregator
    cacheDir: /var/lib/m3kv
    etcdClusters:
      - zone: embedded
        endpoints:
          - *
          - *
          - *

runtimeOptions:
  kvConfig:
    environment: default_env
    zone: embedded
  writeValuesPerMetricLimitPerSecondKey: write-values-per-metric-limit-per-second
  writeValuesPerMetricLimitPerSecond: 0
  writeNewMetricLimitClusterPerSecondKey: write-new-metric-limit-cluster-per-second
  writeNewMetricLimitClusterPerSecond: 0
  writeNewMetricNoLimitWarmupDuration: 0

aggregator:
  bufferDurationForPastTimedMetric: 30m
  bufferDurationForFutureTimedMetric: 30m
  hostID:
    resolver: hostname
  instanceID:
    type: host_id
  metricPrefix: ""
  counterPrefix: ""
  timerPrefix: ""
  gaugePrefix: ""
  aggregationTypes:
    counterTransformFnType: empty
    timerTransformFnType: suffix
    gaugeTransformFnType: empty
    aggregationTypesPool:
      size: 1024
    quantilesPool:
      buckets:
        - count: 256
          capacity: 4
        - count: 128
          capacity: 8
  stream:
    eps: 0.001
    capacity: 32
    streamPool:
      size: 4096
    samplePool:
      size: 4096
    floatsPool:
      buckets:
        - count: 4096
          capacity: 16
        - count: 2048
          capacity: 32
        - count: 1024
          capacity: 64
  client:
    placementKV:
      namespace: /placement
      zone: embedded
      environment: default_env
    placementWatcher:
      key: m3aggregator
      initWatchTimeout: 15s
    hashType: murmur32
    shardCutoffLingerDuration: 1m
    encoder:
      initBufferSize: 100
      maxMessageSize: 50000000
      bytesPool:
        buckets:
          - capacity: 16
            count: 10
          - capacity: 32
            count: 20
        watermark:
          low: 0.001
          high: 0.01
    flushSize: 1440
    maxTimerBatchSize: 140
    queueSize: 1000
    queueDropType: oldest
    connection:
      connectionTimeout: 1s
      connectionKeepAlive: true
      writeTimeout: 1s
      initReconnectThreshold: 2
      maxReconnectThreshold: 5000
      reconnectThresholdMultiplier: 2
      maxReconnectDuration: 1m
  placementManager:
    kvConfig:
      namespace: /placement
      environment: default_env
      zone: embedded
    placementWatcher:
      key: m3aggregator
      initWatchTimeout: 10s
  hashType: murmur32
  bufferDurationBeforeShardCutover: 10m
  bufferDurationAfterShardCutoff: 10m
  resignTimeout: 1m
  flushTimesManager:
    kvConfig:
      environment: default_env
      zone: embedded
    flushTimesKeyFmt: shardset/%d/flush
    flushTimesPersistRetrier:
      initialBackoff: 100ms
      backoffFactor: 2.0
      maxBackoff: 2s
      maxRetries: 3
  electionManager:
    election:
      leaderTimeout: 10s
      resignTimeout: 10s
      ttlSeconds: 10
    serviceID:
      name: m3aggregator
      environment: default_env
      zone: embedded
    electionKeyFmt: shardset/%d/lock
    campaignRetrier:
      initialBackoff: 100ms
      backoffFactor: 2.0
      maxBackoff: 2s
      forever: true
      jitter: true
    changeRetrier:
      initialBackoff: 100ms
      backoffFactor: 2.0
      maxBackoff: 5s
      forever: true
      jitter: true
    resignRetrier:
      initialBackoff: 100ms
      backoffFactor: 2.0
      maxBackoff: 5s
      forever: true
      jitter: true
    campaignStateCheckInterval: 1s
    shardCutoffCheckOffset: 30s
  flushManager:
    checkEvery: 1s
    jitterEnabled: true
    maxJitters:
      - flushInterval: 5s
        maxJitterPercent: 1.0
      - flushInterval: 10s
        maxJitterPercent: 0.5
      - flushInterval: 1m
        maxJitterPercent: 0.5
      - flushInterval: 10m
        maxJitterPercent: 0.5
      - flushInterval: 1h
        maxJitterPercent: 0.25
    numWorkersPerCPU: 0.5
    flushTimesPersistEvery: 10s
    maxBufferSize: 5m
    forcedFlushWindowSize: 10s
  flush:
    handlers:
      - dynamicBackend:
          name: m3msg
          hashType: murmur32
          producer:
            buffer:
              maxBufferSize: 1000000000 # max buffer before m3msg start dropping data.
            writer:
              topicName: aggregated_metrics
              topicServiceOverride:
                zone: embedded
                environment: default_env
              messageRetry:
                initialBackoff: 1m
                maxBackoff: 2m
              messageQueueNewWritesScanInterval: 1s
              ackErrorRetry:
                initialBackoff: 2s
                maxBackoff: 10s
              connection:
                dialTimeout: 5s
                writeTimeout: 5s
                retry:
                  initialBackoff: 1s
                  maxBackoff: 10s
                flushInterval: 1s
                writeBufferSize: 16384
                readBufferSize: 256
  forwarding:
    maxSingleDelay: 5s
  entryTTL: 1h
  entryCheckInterval: 10m
  maxTimerBatchSizePerWrite: 140
  defaultStoragePolicies:
    - 5m:30d
  maxNumCachedSourceSets: 2
  discardNaNAggregatedValues: true
  entryPool:
    size: 4096
  counterElemPool:
    size: 4096
  timerElemPool:
    size: 4096
  gaugeElemPool:
    size: 4096
```
M3Coordinator.yaml
```
listenAddress:
  type: "config"
  value: "0.0.0.0:7201"

logging:
  level: info

metrics:
  scope:
    prefix: "coordinator"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:7203
  sanitization: prometheus
  samplingRate: 1.0
  extended: none

tagOptions:
  idScheme: quoted

downsample:
  remoteAggregator:
    client:
      placementKV:
        namespace: /placement
      placementWatcher:
        key: m3aggregator
        initWatchTimeout: 10s
      hashType: murmur32
      shardCutoffLingerDuration: 1m
      flushSize: 1440
      maxTimerBatchSize: 1120
      queueSize: 10000
      queueDropType: oldest
      encoder:
        initBufferSize: 2048
        maxMessageSize: 10485760
        bytesPool:
          buckets:
            - capacity: 2048
              count: 4096
            - capacity: 4096
              count: 4096
          watermark:
            low: 0.7
            high: 1.0
      connection:
        writeTimeout: 250ms
        connectionKeepAlive: true
        initReconnectThreshold: 10
  bufferPastLimits:
    - resolution: 5m
      bufferPast: 30m
ingest:
  ingester:
    workerPoolSize: 100
    opPool:
      size: 100
    retry:
      maxRetries: 3
      jitter: true
    logSampleRate: 0.01
  m3msg:
    server:
      listenAddress: "0.0.0.0:7507"
      retry:
        maxBackoff: 10s
        jitter: true

clusters:
  - namespaces:
      - namespace: default_unaggregated
        type: unaggregated
        retention: 168h
      - namespace: metrics_aggregated_5m_720h
        type: aggregated
        retention: 720h
        resolution: 5m
    client:
      config:
        service:
          env: default_env
          zone: embedded
          service: m3db
          cacheDir: /var/lib/m3kv
          etcdClusters:
            - zone: embedded
              endpoints:
                - *
                - *
                - *
      writeConsistencyLevel: majority
      readConsistencyLevel: unstrict_majority
      writeTimeout: 10s
      fetchTimeout: 15s
      connectTimeout: 20s
      writeRetry:
        initialBackoff: 500ms
        backoffFactor: 3
        maxRetries: 2
        jitter: true
      fetchRetry:
        initialBackoff: 500ms
        backoffFactor: 2
        maxRetries: 3
        jitter: true
      backgroundHealthCheckFailLimit: 4
      backgroundHealthCheckFailThrottleFactor: 0.5
tracing:
  backend: jaeger
  jaeger:
    reporter:
      localAgentHostPort: jaeger-agent.default:6831
    sampler:
      type: probabilistic
      param: 0.1
```
3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?

A: Prometheus remote write and read

4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.

A: After the configuration is completed, this error can occur after accessing prometheus data
