### ISSUE TITLE
Why m3dbnode cluster oom together？

### ISSUE THREAD

**Issue by ning1875** [m3db/m3#2475]
![image](https://user-images.githubusercontent.com/20356568/88145538-2421a200-cc2d-11ea-982a-acf7bffddc79.png)

The nodes in the cluster will occasionally oom together, the process is very violent, and the sys state cpu will be high, it should be allocating memory, and then oom. Since the process is very short, I cannot capture the pprof information. I also tried to check whether there is a heavy-query from all the query statements, but I didn’t find it.

Here are m3dbnode info 
```
# /usr/bin/m3dbnode  --version
2020/07/22 15:10:22 Go Runtime version: go1.13.8
2020/07/22 15:10:22 Build Version:      v0.15.4
2020/07/22 15:10:22 Build Revision:     4401470a3
2020/07/22 15:10:22 Build Branch:       master
2020/07/22 15:10:22 Build Date:         2020-07-01-00:49:35
2020/07/22 15:10:22 Build TimeUnix:     1593578975
flag provided but not defined: -version
Usage of /usr/bin/m3dbnode:
  -d	Dump configuration and exit
  -f value
    	Configuration files to load
```

Here are my  m3dbnode.yaml
```
coordinator:
  listenAddress:
    type: "config"
    value: "0.0.0.0:7201"
  local:
    namespaces:
        - namespace: default
          type: unaggregated
          retention: 360h
  metrics:
    scope:
      prefix: "coordinator"
    prometheus:
      handlerPath: /metrics
      listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
    sanitization: prometheus
    samplingRate: 1.0
    extended: detailed
  tagOptions:
    idScheme: quoted

db:
  logging:
    level: error
    file: "/m3/log/m3db"

  metrics:
    prometheus:
      handlerPath: /metrics
    sanitization: prometheus
    samplingRate: 1.0
    extended: detailed

  hostID:
    resolver: hostname

  listenAddress: 0.0.0.0:9000
  clusterListenAddress: 0.0.0.0:9001
  httpNodeListenAddress: 0.0.0.0:9002
  httpClusterListenAddress: 0.0.0.0:9003
  debugListenAddress: 0.0.0.0:9004

  client:
    writeConsistencyLevel: majority
    readConsistencyLevel: unstrict_majority

  gcPercentage: 100

  writeNewSeriesAsync: true
  writeNewSeriesLimitPerSecond: 1048576
  writeNewSeriesBackoffDuration: 2ms

  bootstrap:
    bootstrappers:
        - filesystem
        - commitlog
        - peers
        - uninitialized_topology
    fs:
        numProcessorsPerCPU: 0.125
    commitlog:
        returnUnfulfilledForCorruptCommitLogFiles: false
        
  cache:
    series:
      policy: lru
    postingsList:
      size: 262144

  commitlog:
    flushMaxBytes: 524288
    flushEvery: 1s
    queue:
        calculationType: fixed
        size: 2097152

  fs:
    filePathPrefix: /m3/lib/m3db

  config:
    service:
      env: default_env
      zone: embedded
      service: m3db
      cacheDir: /m3/lib/m3kv
      etcdClusters:
        - zone: embedded
          endpoints:
            - xxx.etcd:2379
            - xxx.etcd:2379
            - xxx.etcd:2379

```
