### ISSUE TITLE
Inconsistent read results

### ISSUE THREAD

**Issue by shoopdedoop** [m3db/m3#2486]
1. What service is experiencing the issue? (M3Coordinator, M3DB, M3Aggregator, etc)

M3Coordinator/ m3query

2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).

Running in kubernetes with 3 m3db pods and 3 coordinator pods.

Coordinator Config:
```
  m3coordinator.yml: |
    listenAddress:
      type: "config"
      value: "0.0.0.0:7201"
    local:
      namespaces:
      - namespace: default
        type: unaggregated
        retention: 168h

    metrics:
      scope:
        prefix: "coordinator"
      prometheus:
        handlerPath: /metrics
        listenAddress: 0.0.0.0:7203
      sanitization: prometheus
      samplingRate: 1.0
      extended: none
    tagOptions:
      idScheme: quoted

    clusters:
      - namespaces:
          - namespace: default
            type: unaggregated
            retention: 48h
        client:
          config:
            service:
              env: "master-monitoring-services/master-monitoring-services-m3db-cluster-pv"
              zone: embedded
              service: m3db
              cacheDir: /var/lib/m3kv
              etcdClusters:
                - zone: embedded
                  endpoints:
                  - "http://etcd-0.etcdm3db.mm-global:2379"
                  - "http://etcd-1.etcdm3db.mm-global:2379"
                  - "http://etcd-2.etcdm3db.mm-global:2379"
          writeConsistencyLevel: majority
          readConsistencyLevel: unstrict_majority
```

 M3DB Config:

```
   m3.yml: |
    db:
      repair:
        enabled: false

      logging:
        level: info

      metrics:
        prometheus:
          handlerPath: /metrics
        sanitization: prometheus
        samplingRate: 1.0
        extended: detailed

      listenAddress: 0.0.0.0:9000
      clusterListenAddress: 0.0.0.0:9001
      httpNodeListenAddress: 0.0.0.0:9002
      httpClusterListenAddress: 0.0.0.0:9003
      debugListenAddress: 0.0.0.0:9004

      hostID:
        resolver: file
        file:
          path: /etc/m3db/pod-identity/identity
          timeout: 5m


      client:
        writeConsistencyLevel: majority
        readConsistencyLevel: unstrict_majority

      gcPercentage: 100

      writeNewSeriesAsync: true
      writeNewSeriesLimitPerSecond: 1048576
      writeNewSeriesBackoffDuration: 2ms

      cache:
        series:
          policy: none

      bootstrap:
        bootstrappers:
            - filesystem
            - commitlog
            - peers
            - uninitialized_topology
        fs:
            numProcessorsPerCPU: 0.125
        commitlog:
            # https://docs.m3db.io/operational_guide/availability_consistency_durability/
            returnUnfulfilledForCorruptCommitLogFiles: false

      commitlog:
        flushMaxBytes: 524288
        flushEvery: 5s
        queue:
            calculationType: fixed
            size: 2097152

      fs:
        filePathPrefix: /var/lib/m3db

      pooling:
        blockAllocSize: 16
        type: simple
        seriesPool:
          size: 64000
          lowWatermark: 0.7
          highWatermark: 1.0
        blockPool:
          size: 64000
          lowWatermark: 0.7
          highWatermark: 1.0
        encoderPool:
          size: 130000
          lowWatermark: 0.7
          highWatermark: 1.0
        closersPool:
          size: 52000
          lowWatermark: 0.7
          highWatermark: 1.0
        contextPool:
          size: 65536
          lowWatermark: 0.7
          highWatermark: 1.0
        segmentReaderPool:
          size: 4096
          lowWatermark: 0.7
          highWatermark: 1.0
        iteratorPool:
          size: 512
          lowWatermark: 0.7
          highWatermark: 1.0
        fetchBlockMetadataResultsPool:
          size: 16384
          capacity: 32
          lowWatermark: 0.7
          highWatermark: 1.0
        fetchBlocksMetadataResultsPool:
          size: 32
          capacity: 4096
          lowWatermark: 0.7
          highWatermark: 1.0
        blockMetadataPool:
          size: 16384
          lowWatermark: 0.7
          highWatermark: 1.0
        blockMetadataSlicePool:
          size: 16384
          capacity: 32
          lowWatermark: 0.7
          highWatermark: 1.0
        blocksMetadataPool:
          size: 16384
          lowWatermark: 0.7
          highWatermark: 1.0
        blocksMetadataSlicePool:
          size: 32
          capacity: 4096
          lowWatermark: 0.7
          highWatermark: 1.0
        identifierPool:
          size: 262144
          lowWatermark: 0.7
          highWatermark: 1.0
        bytesPool:
          buckets:
            - capacity: 16
              size: 131072
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 32
              size: 65536
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 64
              size: 32768
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 128
              size: 16384
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 256
              size: 16384
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 1440
              size: 4096
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 1024
              size: 8192
              lowWatermark: 0.7
              highWatermark: 1.0

      config:
        service:
            env: "master-monitoring-services/master-monitoring-services-m3db-cluster-pv"
            zone: embedded
            service: m3db
            cacheDir: /var/lib/m3kv
            etcdClusters:
            - zone: embedded
              endpoints:
              - "http://etcd-0.etcdm3db.mm-global:2379"
              - "http://etcd-1.etcdm3db.mm-global:2379"
              - "http://etcd-2.etcdm3db.mm-global:2379"
```
3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?

Prometheus is performing a remote write to m3 and grafana is performing reads to m3.

4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.

It seems that when performing read queries againt m3 the order of the results can change from one query to the next.

For example in my case I run the following.

```
avg_over_time(node_memory_MemTotal{instance=~"(a|pp).*"}[5m])

{instance="a1",job="node-exporter"}	63037747200
{instance="a2",job="node-exporter"}	63037747200
{instance="a3",job="node-exporter"}	63037747200
{instance="pp1",job="node-exporter"}	31331823616
{instance="pp2",job="node-exporter"}	31331823616
{instance="pp3",job="node-exporter"}	31331823616
{instance="pp4",job="node-exporter"}	31331823616
{instance="pp5",job="node-exporter"}	31331823616
{instance="pp6",job="node-exporter"}	31331823616
{instance="pp7",job="node-exporter"}	31331823616
{instance="pp8",job="node-exporter"}	31331823616
{instance="pp9",job="node-exporter"}	31331823616
```

Next query may return

```
{instance="pp7",job="node-exporter"}	31331823616
{instance="pp8",job="node-exporter"}	31331823616
{instance="pp9",job="node-exporter"}	31331823616
{instance="a1",job="node-exporter"}	63037747200
{instance="a2",job="node-exporter"}	63037747200
{instance="a3",job="node-exporter"}	63037747200
{instance="pp1",job="node-exporter"}	31331823616
{instance="pp2",job="node-exporter"}	31331823616
{instance="pp3",job="node-exporter"}	31331823616
{instance="pp4",job="node-exporter"}	31331823616
{instance="pp5",job="node-exporter"}	31331823616
{instance="pp6",job="node-exporter"}	31331823616
```

This causes incorrect calculations when you have multiple executions of that query...for example

```
ceil(100 * ((avg_over_time(node_memory_MemTotal{instance=~"(a|pp).*"}[5m]) - avg_over_time(node_memory_MemAvailable{instance=~"(a|pp).*"}[5m])) / avg_over_time(node_memory_MemTotal{instance=~"(a|pp).*"}[5m])))
```

From what I can tell if you execute avg_over_time(node_memory_MemTotal{instance=~"(a|pp).*"}[5m]) the order of the result is always different while if you execute the same query against prometheus the order of the results is always the same.

Given that the order is different with m3 then each of the above avg_over_time commands comes back with a different order causing the calculations to be inconsistent from one execution to the next.
