### ISSUE TITLE
m3query container startup error

### ISSUE THREAD

**Issue by victorca25** [m3db/m3#2940]
1. What service is experiencing the issue? 
M3Query

2. What is the configuration of the service? 

```
listenAddress:
  value: "0.0.0.0:7201"

logging:
  level: info

metrics:
  scope:
    prefix: "coordinator"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:7203
  sanitization: prometheus
  samplingRate: 1.0
  extended: none

tagOptions:
  idScheme: quoted

clusters:
  - namespaces:
      - namespace: default
        retention: 48h
        type: unaggregated
    client:
      config:
        service:
          env: default_env
          zone: embedded
          service: m3db
          cacheDir: /var/lib/m3kv
          etcdClusters:
            - zone: embedded
              endpoints:
                - m3db-etc-01.nix.com:2379
                - m3db-etc-02.nix.com:2379
                - m3db-etc-03.nix.com:2379
                - m3db-etc-04.nix.com:2379
#        seedNodes:
#          initialCluster:
#            - hostID: m3db_local
#              endpoint: http://127.0.0.1:2380
      writeConsistencyLevel: majority
      readConsistencyLevel: unstrict_majority
      writeTimeout: 10s
      # fetchTimeout defines the fetch timeout for any given query.
      # The default is 30s and the max is 5m.
      fetchTimeout: 30s
      connectTimeout: 20s
      writeRetry:
        initialBackoff: 500ms
        backoffFactor: 3
        maxRetries: 2
        jitter: true
      fetchRetry:
        initialBackoff: 500ms
        backoffFactor: 2
        maxRetries: 3
        jitter: true
      backgroundHealthCheckFailLimit: 4
      backgroundHealthCheckFailThrottleFactor: 0.5

readWorkerPoolPolicy:
  grow: false
  size: 10

writeWorkerPoolPolicy:
  grow: false
  size: 10

# Query configuration.
query:
  timeout: 30s
  # The default query engine is 'prometheus' but it could be switched to 'm3query'
  defaultEngine: prometheus
```

When starting the m3query docker container with the configuration, the following is the output log:
```
2020/11/23 09:45:50 Build Version:      v1.0.0
2020/11/23 09:45:50 Build Revision:     a3853ee56
2020/11/23 09:45:50 Build Branch:       HEAD
2020/11/23 09:45:50 Build Date:         2020-11-17-23:23:36
2020/11/23 09:45:50 Build TimeUnix:     1605655416
error loading config: unable to load config from [/etc/m3query/m3query.yml]: yaml: unmarshal errors:
  line 38: cannot unmarshal !!map into string
```

This same configuration was working last week and no changes were made, the container was only recreated and now its not coming up. Any suggestions what could be the reason?
