### ISSUE TITLE
M3db query is too slow

### ISSUE THREAD

**Issue by wang1219** [m3db/m3#3032]
My prometheus uses M3db remote storage, but the execution time of the alarm is getting longer and longer, the query is getting slower and slower, and it will be restored when the index is updated.

My cluster will update the index every day at 00:00 08:00 16:00.

prometheus_rule_evaluation_duration_seconds
![image](https://user-images.githubusercontent.com/18459440/102751765-56355c80-43a3-11eb-9630-808515bd5c33.png)

**Comment by gibbscullen** [comment]
@arnikola - thoughts here?

**Comment by gibbscullen** [comment]
@wang1219 -- what is your blocksize for this?

**Comment by robskillington** [comment]
This looks like a misconfigured block size (8hrs) with very dense datapoints per second (probably <= datapoint per second)? 

Essentially the smallest granularity of data you can pull back from a series is a single block, so if you create super dense blocks when you setup the DB instead of using defaults this is possible.

What is the frequency of writes and can you confirm you are using a 8hr block size? Also what is the cardinality of these queries and the start/end params on the query?

I'll close this until further details are shared, feel free to reopen and we can look at this further.

Thanks.

**Comment by wang1219** [comment]
@robskillington Thank you for your reply. In order to update the index faster, I modified blockSizeDuration, but some problems occurred, reference https://github.com/m3db/m3/issues/2789#issuecomment-751167123, But I just changed the indexOptions blockSizeDuration back to 8h.

These queries all come from Prometheus alarm queries.

I guess it may have something to do with the LRU caching strategy I use, because it will be restored as the index is updated

This is the monitoring of m3coordinator `coordinator_m3db_client_fetch_req_success_latency`
![image](https://user-images.githubusercontent.com/18459440/106845470-f2ae8680-66e5-11eb-9cf7-1cacfe66a2f9.png)

This is the monitoring of m3coordinator `rate(coordinator_m3db_client_fetch_req_success{job="m3coordinator", instance=~"$instance"}[2m])`
![image](https://user-images.githubusercontent.com/18459440/106845750-8b450680-66e6-11eb-9b7c-d344b5b63cd9.png)



This is my namespace config
```
{
    "registry":{
        "namespaces":{
            "metrics":{
                "bootstrapEnabled":true,
                "flushEnabled":true,
                "writesToCommitLog":true,
                "cleanupEnabled":true,
                "repairEnabled":false,
                "retentionOptions":{
                    "retentionPeriodNanos":"10368000000000000",
                    "blockSizeNanos":"14400000000000",
                    "bufferFutureNanos":"600000000000",
                    "bufferPastNanos":"600000000000",
                    "blockDataExpiry":true,
                    "blockDataExpiryAfterNotAccessPeriodNanos":"300000000000",
                    "futureRetentionPeriodNanos":"0"
                },
                "snapshotEnabled":true,
                "indexOptions":{
                    "enabled":true,
                    "blockSizeNanos":"28800000000000"
                },
                "schemaOptions":null,
                "coldWritesEnabled":false,
                "runtimeOptions":null
            }
        }
    }
}
```

My m3 node config
```
coordinator:
  listenAddress:
    type: "config"
    value: "0.0.0.0:7201"

  local:
    namespaces:
      - namespace: default
        type: unaggregated
        retention: 48h

  metrics:
    scope:
      prefix: "coordinator"
    prometheus:
      handlerPath: /metrics
      listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
    sanitization: prometheus
    samplingRate: 1.0
    extended: none

  tagOptions:
    # Configuration setting for generating metric IDs from tags.
    idScheme: legacy

db:
  logging:
    level: info

  metrics:
    prometheus:
      handlerPath: /metrics
      listenAddress: 0.0.0.0:7204
    sanitization: prometheus
    samplingRate: 1.0
    extended: detailed

  hostID:
    resolver: hostname

# Fill-out the following and un-comment before using.
  config:
    service:
      env: default_env
      zone: embedded
      service: m3db
      cacheDir: /var/lib/m3kv
      etcdClusters:
        - zone: embedded
          endpoints:
            - etcd-ip1:2379
            - etcd-ip2:2379
            - etcd-ip3:2379
    seedNodes:
      initialCluster:
        - hostID: etcd-hostname1
          endpoint: http://etcd-ip1:2380
        - hostID: etcd-hostname2
          endpoint: http://etcd-ip2:2380
        - hostID: etcd-hostname3
          endpoint: http://etcd-ip3:2380


  listenAddress: 0.0.0.0:9000
  clusterListenAddress: 0.0.0.0:9001
  httpNodeListenAddress: 0.0.0.0:9002
  httpClusterListenAddress: 0.0.0.0:9003
  debugListenAddress: 0.0.0.0:9004

  client:
    writeConsistencyLevel: majority
    readConsistencyLevel: unstrict_majority

  gcPercentage: 100

  writeNewSeriesAsync: true
  writeNewSeriesLimitPerSecond: 1048576
  writeNewSeriesBackoffDuration: 2ms

  bootstrap:
    bootstrappers:
        - filesystem
        - commitlog
        - peers
        - uninitialized_topology
    fs:
      numProcessorsPerCPU: 0.125
    commitlog:
      returnUnfulfilledForCorruptCommitLogFiles: false

  cache:
    series:
      policy: lru
    postingsList:
      size: 262144

  commitlog:
    flushMaxBytes: 524288
    flushEvery: 1s
    queue:
      calculationType: fixed
      size: 2097152

  fs:
    filePathPrefix: /var/lib/m3db
```

My m3coordinator config
```
listenAddress:
  type: "config"
  value: "0.0.0.0:7201"

metrics:
  scope:
    prefix: "coordinator"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
  sanitization: prometheus
  samplingRate: 1.0
  extended: none
tagOptions:
  idScheme: legacy

limits:
  maxComputedDatapoints: 1000000
  perQuery:
    maxFetchedSeries: 100000

clusters:
   - namespaces:
# We created a namespace called "default" and had set it to retention "48h".
       - namespace: metrics
         retention: 48h
         type: unaggregated
       #- namespace: metrics_360s_720h
       #  type: aggregated
       #  retention: 720h
       #  resolution: 360s
     client:
       config:
         service:
           env: default_env
           zone: embedded
           service: m3db
           cacheDir: /var/lib/m3kv
           etcdClusters:
             - zone: embedded
               endpoints:
# We have five M3DB nodes but only three are seed nodes, they are listed here.
                 - etcd-ip1:2379
                 - etcd-ip2:2379
                 - etcd-ip3:2379
       writeConsistencyLevel: majority
       readConsistencyLevel: unstrict_majority
       writeTimeout: 10s
       fetchTimeout: 15s
       connectTimeout: 20s
       writeRetry:
         initialBackoff: 500ms
         backoffFactor: 3
         maxRetries: 2
         jitter: true
       fetchRetry:
         initialBackoff: 500ms
         backoffFactor: 2
         maxRetries: 3
         jitter: true
       backgroundHealthCheckFailLimit: 4
       backgroundHealthCheckFailThrottleFactor: 0.5
```
