### ISSUE TITLE
Disconnected Traces between M3Query and M3DBNode

### ISSUE THREAD

**Issue by albertteoh** [m3db/m3#3136]
We came across a situation where a single request to an M3 endpoint resulted in two traces being created, when we expected a single trace. An example of traces resulting from a request to the query_range endpoint looks like the following and I've circled what I believe should be the continuation points of each trace:

![Screen Shot 2021-01-28 at 8 19 53 pm](https://user-images.githubusercontent.com/26584478/106250374-a687c000-6267-11eb-8d58-d448732408f3.png)
![Screen Shot 2021-01-28 at 8 22 49 pm](https://user-images.githubusercontent.com/26584478/106250386-ab4c7400-6267-11eb-9009-ebad6c3a8bd4.png)

I suspect the broken trace is caused by trace context being lost due to it not being passed down, and the creation of a new Context within an async operation on this line of code: https://github.com/m3db/m3/blob/master/src/dbnode/client/host_queue.go#L879

1. What service is experiencing the issue? (M3Coordinator, M3DB, M3Aggregator, etc)

This example is specific to M3Query -> M3DB, but could apply to other services.

2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).

**m3query.yml**
```
listenAddress: 0.0.0.0:7202

tracing:
  backend: jaeger
  jaeger:
    sampler:
      type: remote

clusters:
  - namespaces:
      - namespace: default
        type: unaggregated
        retention: 48h
    client:
      config:
        service:
          env: default_env
          zone: embedded
          service: m3db
          cacheDir: /var/lib/m3kv
          etcdClusters:
            - zone: embedded
              endpoints:
                - 127.0.0.1:2379
metrics:
  scope:
    prefix: "query"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:7204 # until https://github.com/m3db/m3/issues/682 is resolved
  sanitization: prometheus
  samplingRate: 1.0
  extended: none
```

**m3dbnode.yml**
```
coordinator:
  tracing:
    backend: jaeger
    jaeger:
      sampler:
        type: const
        param: 1
db:
  tracing:
    backend: jaeger
    jaeger:
      sampler:
        type: remote
```

3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?

Custom script to read and write.

**write_sample_data.sh**
```
curl -X POST http://localhost:7201/api/v1/json/write -d '{
  "tags":
    {
      "__name__": "third_avenue",
      "city": "boston",
      "checkout": "1"
    },
    "timestamp": '\"$(date "+%s")\"',
    "value": 3347.26
}'

# Insert tagged data
curl http://localhost:9003/writetagged -s -X POST -d '{
  "namespace": "default",
  "id": "foo",
  "tags": [
    {
      "name": "__name__",
      "value": "user_login"
    },
    {
      "name": "city",
      "value": "new_york"
    },
    {
      "name": "endpoint",
      "value": "/request"
    }
  ],
  "datapoint": {
    "timestamp":'"$(date +"%s")"',
    "value": 42.123456789
  }
}'
```

**query_sample_data.sh**
```
curl -X "POST" -G "http://localhost:7202/api/v1/query_range" \
  -d "query=third_avenue" \
  -d "start=$( date -v -45S +%s )" \
  -d "end=$( date +%s )" \
  -d "step=5s" | jq .
```

4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.
   1. Start [Jaeger all-in-one](https://www.jaegertracing.io/docs/1.21/getting-started/#all-in-one). I personally ran each component from source as I wanted to filter out `Node::health` traces.

   1. Run m3dbnode: 

          
          make m3dbnode

          sudo ./bin/m3dbnode -f m3dbnode.yml
          

   2. Run 

          make m3query

          sudo ./bin/m3query -f md3query.yml

   3. Write some data: 

          ./write_sample_data.sh

   4. Query the data

          ./query_sample_data.sh

   5. Search for m3query traces in Jaeger: http://localhost:16686. Results in two traces for the single query:
![Screen Shot 2021-01-28 at 7 45 33 pm](https://user-images.githubusercontent.com/26584478/106250233-7a6c3f00-6267-11eb-9d78-790b7ddac1c3.png)

   6. Drilling into each trace, we see that one trace is a continuation of the other as in the screenshots at the top of this Issue.
