### ISSUE TITLE
Breaking changes in minor release not documented

### ISSUE THREAD

**Issue by pickfire** [m3db/m3#3175]
# Filing M3 Issues

## General Issues

General issues are any non-performance related issues (data integrity, ease of use, error messages, configuration, documentation, etc).

Please provide the following information along with a description of the issue that you're experiencing:

1. What service is experiencing the issue? m3dbnode
2. What is the configuration of the service?
```yaml
coordinator:
  listenAddress:
    value: "0.0.0.0:7201"

  local:
    namespaces:
      - namespace: default
        type: unaggregated
        retention: 48h

  logging:
    level: error

  metrics:
    scope:
      prefix: "coordinator"
    prometheus:
      handlerPath: /metrics
      listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
    sanitization: prometheus
    samplingRate: 1.0
    extended: none

  limits:
    maxComputedDatapoints: 10000

  tagOptions:
    # Configuration setting for generating metric IDs from tags.
    idScheme: quoted

db:
  logging:
    level: info

  metrics:
    prometheus:
      handlerPath: /metrics
    sanitization: prometheus
    samplingRate: 1.0
    extended: detailed

  listenAddress: 0.0.0.0:9000
  clusterListenAddress: 0.0.0.0:9001
  httpNodeListenAddress: 0.0.0.0:9002
  httpClusterListenAddress: 0.0.0.0:9003
  debugListenAddress: 0.0.0.0:9004

  hostID:
    resolver: config
    value: m3db_local

  client:
    writeConsistencyLevel: majority
    readConsistencyLevel: unstrict_majority

  gcPercentage: 100

  writeNewSeriesAsync: true
  writeNewSeriesLimitPerSecond: 1048576
      writeNewSeriesBackoffDuration: 2ms
        
      bootstrap:
        bootstrappers:
            - filesystem
            - commitlog
            - peers
            - uninitialized_topology
        commitlog:
          returnUnfulfilledForCorruptCommitLogFiles: false
        
      cache:
        series:
          policy: lru
        postingsList:
          size: 262144
          
      commitlog:
        flushMaxBytes: 524288
        flushEvery: 1s
        queue:
          calculationType: fixed
          size: 2097152
        
      fs:
        filePathPrefix: /var/lib/m3db
        
      config:
          service:
              env: default_env
              zone: embedded
              service: m3db
              cacheDir: /var/lib/m3kv
              etcdClusters:
                  - zone: embedded
                    endpoints:
                        - 127.0.0.1:2379
          seedNodes:
              initialCluster:
                  - hostID: m3db_local
                    endpoint: http://127.0.0.1:2380
      
      # un-comment the lines below to enable Jaeger tracing. See https://www.jaegertracing.io/docs/1.9/getting-started/
      # for quick local setup (which this config will send data to).
      
      # tracing:
      #  backend: jaeger
```
3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script? I am using kubernetes to deploy
4. Is there a reliable way to reproduce the behavior? Use that as a config for m3db deployment and add the following to statefulset.
```yaml
volumes:
- name: config-vol
  configMap:
    name: m3dbnode-config
```

Because we were using `latest` for development, we noticed this breaking after yesterday releases.
```
2021/02/05 03:31:15 Go Runtime version: go1.13.15
2021/02/05 03:31:15 Build Version:      v1.1.0
2021/02/05 03:31:15 Build Revision:     468ab1c4b
2021/02/05 03:31:15 Build Branch:       HEAD
2021/02/05 03:31:15 Build Date:         2021-02-04-20:27:35
2021/02/05 03:31:15 Build TimeUnix:     1612470455
2021-02-05 03:31:15.188984 I | error loading config: unable to load config from [/etc/m3db/m3dbnode.yml]: yaml: unmarshal errors:
  line 3: field maxComputedDatapoints not found in type config.LimitsConfiguration
  line 5: cannot unmarshal !!map into string
  line 26: field bootstrappers not found in type config.BootstrapConfiguration
  line 48: field config not found in type config.DBConfiguration
  line 63: field fs not found in type config.DBConfiguration
  line 82: field writeNewSeriesLimitPerSecond not found in type config.DBConfiguration
```

I wonder why the breaking changes aren't done in major versions and as well not documented in the changelog and release notes. Maybe we should add the breaking changes to the release notes?

Either way, I got it solved by taking the latest config from the repository but these should ideally be documented or done in the major version, otherwise a good thing is to provide backward compatibility by allowing the old fields to be used despite name changes.
