### ISSUE TITLE
initializing value error (key='/namespaces'): init watch timeout

### ISSUE THREAD

**Issue by nk-designz** [m3db/m3#3352]
Hi,
I'm currently writing on a Ansible role/playbook for M3.
But the ```default``` namespace is staying on ```INITIALIZING``` on all it's shards (64).
After a while I noticed this line in the logs:
```json
{"level":"error","ts":1615801621.4921045,"msg":"error initializing namespaces values, retrying in the background","key":"/namespaces","error":"initializing value error (key='/namespaces'): init watch timeout"}
```
from
```json
{"level":"info","ts":1616418223.4911308,"msg":"creating etcd watch at revision","watch_key":"_kv/default_env//namespaces","revision":0}
```
So I checked on the ETCD and no namespaces key could be found.
```bash
etcdctl get --prefix _
```
*_kv/default_env/m3db.node.namespaces*:
```bytes

P
default 2���Ť�	���±4�ຄ� �ॖ�(0����8B      ���±4bj
r
```
*_sd.placement/default_env/m3db*:
```bytes
�

m3db_local�

m3db_locallocalembedded *127.0.0.1:90002222222222
2
 2
2222222222222222222 2!2"2#2$2%2&2'2(2)2*2+2,2-2.2/202122232425262728292:2;2<2=2>2?B	localhostH�FR@ 
```
I would be really thankful for any help.

1. What service is experiencing the issue? (M3Coordinator, M3DB, M3Aggregator, etc)
  - M3DB
2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).
  Configuration:
  ```yaml
coordinator:
  local:
    namespaces:
      - namespace: default
        type: unaggregated
        retention: 48h
db:
  logging:
    level: debug
  hostID:
    resolver: hostname
  discovery:
    config:
      service:
        env: default_env
        etcdClusters:
        - zone: embedded
          endpoints:
          - "http://164.90.xx.x9:2379"
          - "http://207.154.xx.x2:2379"
          - "http://164.90.xx.x3:2379"
        service: m3db
        zone: embedded
  ```
  Namespace:
  ```json
{
  "registry": {
    "namespaces": {
      "default": {
        "bootstrapEnabled": true,
        "flushEnabled": true,
        "writesToCommitLog": true,
        "cleanupEnabled": true,
        "repairEnabled": false,
        "retentionOptions": {
          "retentionPeriodNanos": "43200000000000",
          "blockSizeNanos": "1800000000000",
          "bufferFutureNanos": "120000000000",
          "bufferPastNanos": "600000000000",
          "blockDataExpiry": true,
          "blockDataExpiryAfterNotAccessPeriodNanos": "300000000000",
          "futureRetentionPeriodNanos": "0"
        },
        "snapshotEnabled": true,
        "indexOptions": {
          "enabled": true,
          "blockSizeNanos": "1800000000000"
        },
        "schemaOptions": null,
        "coldWritesEnabled": false,
        "runtimeOptions": null,
        "cacheBlocksOnRetrieve": false,
        "aggregationOptions": {
          "aggregations": [
            {
              "aggregated": false,
              "attributes": null
            }
          ]
        },
        "stagingState": {
          "status": "UNKNOWN"
        },
        "extendedOptions": null
      }
    }
  }
}
  ```
  Placement:
  ```json
  {
  "placement": {
    "instances": {
      "m3db_local": {
        "id": "m3db_local",
        "isolationGroup": "local",
        "zone": "embedded",
        "weight": 1,
        "endpoint": "127.0.0.1:9000",
        "shards": [
          {
            "id": 0,
            "state": "INITIALIZING",
            "sourceId": "",
            "cutoverNanos": "0",
            "cutoffNanos": "0"
          },
          ...
          {
            "id": 63,
            "state": "INITIALIZING",
            "sourceId": "",
            "cutoverNanos": "0",
            "cutoffNanos": "0"
          }
        ],
        "shardSetId": 0,
        "hostname": "localhost",
        "port": 9000,
        "metadata": {
          "debugPort": 0
        }
      }
    },
    "replicaFactor": 1,
    "numShards": 64,
    "isSharded": true,
    "cutoverTime": "0",
    "isMirrored": false,
    "maxShardSetId": 0
  },
  "version": 1
}
  ```
3. How are you using the service?
  The M3DB will be used by multiple Prometheus in read/write-configuration.
4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.
  The error appears every rollout using this configuration.

Thanks.
