### ISSUE TITLE
[coordinator] Can supplement some explanation of rollup rule?

### ISSUE THREAD

**Issue by baozh** [m3db/m3#3389]
We may use m3coordinator's rollup rules to pre-aggregate some timeseries, i read only one article related to this topic:

https://m3db.io/v1.0/docs/operational_guide/mapping_rollup/

but this article doesn't explain how calculation expressions are spliced, what are the grammar rules? for example:

```
    rollupRules:
      - name: "http_request latency by route and git_sha without pod"
        filter: "__name__:http_request_bucket k8s_pod:* le:* git_sha:* route:*"
        transforms:
        - transform:
            type: "Increase"
        - rollup:
            metricName: "http_request_rollup_no_pod_bucket"
            groupBy: ["le", "git_sha", "route", "status_code", "region"]
            aggregations: ["Sum"]
        - transform:
            type: "Add"
```
The rollup rules provided by m3 are not as easy to use as the recording rules of prometheus(refer to https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/).

In addition, how to express the following calculation expression  in m3coordinator's rollup rules?
```
histogram_quantile(0.95, sum(rate(rpc_durations_histogram_seconds_bucket{}[10m])) by (le))
```
