### ISSUE TITLE
m3coordinator - write to multiple M3DB clusters doesn't work for 2 unaggregated namespaces

### ISSUE THREAD

**Issue by aned** [m3db/m3#3438]
Hi folks, 

I followed the doc [How to write to multiple M3DB clusters](https://github.com/m3db/m3/pull/2187/commits/68bf63a4b1742ba3d85a91e6aecc8e98ce45f2bc?short_path=cefff39) to set up writing from a single m3coordinator (fresh build from source) to multiple m3db clusters. 
An issue I've encountered is that I can't use 2 unaggregated namespaces in m3coordinator config, it gives me an error 
```
{"level":"fatal","ts":1619140853.8710625,"msg":"unable to init clusters","error":"unable to connect to clusters: only one unaggregated cluster namespace  can be specified: specified 2","errorVerbose":"only one unaggregated cluster namespace  can be specified: specified 2\nunable to connect to clusters\ngithub.com/m3db/m3/src/query/server.initClusters\n\t/Users/anedoshe/go/src/github.com/m3db/m3/src/query/server/query.go:871\ngithub.com/m3db/m3/src/query/server.Run\n\t/Users/anedoshe/go/src/github.com/m3db/m3/src/query/server/query.go:418\nmain.main\n\t/Users/anedoshe/go/src/github.com/m3db/m3/src/cmd/services/m3coordinator/main/main.go:45\nruntime.main\n\t/Users/anedoshe/.gvm/gos/go1.15.6/src/runtime/proc.go:204\nruntime.goexit\n\t/Users/anedoshe/.gvm/gos/go1.15.6/src/runtime/asm_amd64.s:1374"}
```

Config I'm using: https://gist.github.com/aned/49c4483b5adebd72d593a19ee10da75d
When I change 2nd namespace to 
```
   - namespaces:
       - namespace: some_label_unaggregated_6_months
         retention: 4400h
         type: aggregated
         resolution: 10m
```
it works, but I need to be able to write raw data to 2nd m3db cluster (different namespace). 

Also, in the doc [How to write to multiple M3DB clusters](https://github.com/m3db/m3/pull/2187/commits/68bf63a4b1742ba3d85a91e6aecc8e98ce45f2bc?short_path=cefff39) it's not clear how to properly setup `clusterManagement:` when you have 2 different clusters, is this the right config? 

```
clusterManagement:
  etcd:
    env: default_env
    zone: embedded
    service: m3db
    cacheDir: /mnt/u001/content/data/m3db/data
    etcdClusters:
      - zone: embedded
        endpoints:
          - IP-1:2379
          - IP-2:2379
          - IP-3:2379
      - zone: embedded  # Not sure if it's the right way to configure 2nd cluster
        endpoints:
          - IP-4:2379
          - IP-5:2379
          - IP-6:2379
          - IP-7:2379
```
