### ISSUE TITLE
write metrics using http json API only once，But m3query can look up five minutes of metrics。

### ISSUE THREAD

**Issue by crazy-pizza** [m3db/m3#3650]
Expect to see only one metric at write time.

```
curl -X POST http://localhost:7201/api/v1/json/write -d '{
  "tags":
    {
      "__name__": "third_avenue",
      "city": "new_york",
      "checkout": "1"
    },
    "timestamp": '\"$(date "+%s")\"',
    "value": 3347.26
}'
```
```
curl -X "POST" -G "http://localhost:7201/api/v1/query_range"   -d "query=third_avenue"   -d "start=$(date "+%s" -d "45 seconds ago")"   -d "end=$( date +%s )"   -d "step=1s" | jq .
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {
          "__name__": "third_avenuev2",
          "checkout": "1",
          "city": "new_york"
        },
        "values": [
          [
            1628247163,
            "3347.26"
          ],
          [
            1628247164,
            "3347.26"
          ],
          [
            1628247165,
            "3347.26"
          ],
          [
            1628247166,
            "3347.26"
          ],
          [
            1628247167,
            "3347.26"
          ],
          [
            1628247168,
            "3347.26"
          ],
          [
            1628247169,
            "3347.26"
          ],
          [
            1628247170,
            "3347.26"
          ],
          [
            1628247171,
            "3347.26"
          ],
          [
            1628247172,
            "3347.26"
          ],
          [
            1628247173,
            "3347.26"
          ],
          [
            1628247174,
            "3347.26"
          ],
          [
            1628247175,
            "3347.26"
          ],
          [
            1628247176,
            "3347.26"
          ],
          [
            1628247177,
            "3347.26"
          ],
          [
            1628247178,
            "3347.26"
          ],
          [
            1628247179,
            "3347.26"
          ],
          [
            1628247180,
            "3347.26"
          ],
          [
            1628247181,
            "3347.26"
          ]
        ]
      }
    ]
  }
}
```

**Comment by crazy-pizza** [comment]
here are my config. Is it my wrong configuration by cause?
m3db version: 1.1.0

m3coordinator.yml
```
listenAddress: 0.0.0.0:7201
logging:
  level: info
clusters:
  - namespaces:
      - namespace: default
        retention: 720h
        type: unaggregated
    client:
      config:
        service:
            env: default_env
            zone: embedded
            service: m3db
            etcdClusters:
                - zone: embedded
                  endpoints:
                     - x1:2379
                     - x2:2379
                     - x3:2379
      writeConsistencyLevel: majority
      readConsistencyLevel: unstrict_majority
```
m3dbnode.yml
```
db:
  logging:
    level: info

  metrics:
    prometheus:
      handlerPath: /metrics
      listenAddress: 0.0.0.0:7204
    sanitization: prometheus
    samplingRate: 1.0
    extended: detailed

  listenAddress: 0.0.0.0:9000
  clusterListenAddress: 0.0.0.0:9001
  httpNodeListenAddress: 0.0.0.0:9002
  httpClusterListenAddress: 0.0.0.0:9003
  debugListenAddress: 0.0.0.0:9004

  hostID:
    resolver: config
    value: m3db168

  client:
    writeConsistencyLevel: majority
    readConsistencyLevel: unstrict_majority
    writeTimeout: 10s
    fetchTimeout: 15s
    connectTimeout: 20s
    writeRetry:
        initialBackoff: 500ms
        backoffFactor: 3
        maxRetries: 2
        jitter: true
    fetchRetry:
        initialBackoff: 500ms
        backoffFactor: 2
        maxRetries: 3
        jitter: true
    backgroundHealthCheckFailLimit: 4
    backgroundHealthCheckFailThrottleFactor: 0.5


  writeNewSeriesAsync: true
  writeNewSeriesBackoffDuration: 2ms

  filesystem:
    filePathPrefix: /opt/work/m3db

  discovery:
    config:
        service:
            env: default_env
            zone: embedded
            service: m3db
            # etcd集群配置
            cacheDir: /opt/work/m3db/data
            etcdClusters:
                - zone: embedded
                  endpoints:
                     - x1:2379
                     - x2:2379
                     - x3:2379
```
