### ISSUE TITLE
proto decoded message size 1195986768 is larger than maximum supported size 4194304

### ISSUE THREAD

**Issue by crazy-pizza** [m3db/m3#3773]
There are many errors in the M3Coordinator log. What do these errors 
```
{"level":"error","ts":1632119119.2488701,"msg":"could not read message from consumer","error":"unexpected EOF"}
{"level":"error","ts":1632119119.2520366,"msg":"could not read message from consumer","error":"proto: illegal wireType 7"}
{"level":"error","ts":1632119119.2557118,"msg":"could not read message from consumer","error":"proto decoded message size 1811942144 is larger than maximum supported size 4194304"}
```

**Comment by wesleyk** [comment]
Not quite sure which integration you're talking about, but for the coord -> agg interaction you can configure the max message size like so:

```
downsample:
  remoteAggregator:
    client:
      encoder:
        maxMessageSize: <size>
```
