### ISSUE TITLE
Rollup rules not working with unagregated namespace

### ISSUE THREAD

**Issue by yackushevas** [m3db/m3#4073]
https://m3db.io/docs/operational_guide/mapping_rollup/
Based on this documentation, I tried to use the rules for unaggregated namespace:

m3coordinator:
```
    ...
    clusters:
    - namespaces:
      - namespace: default
        retention: 744h
        type: unaggregated
      - namespace: metrics_5m_90d
        retention: 2160h
        resolution: 5m
    ...
    downsample:
      ...
      rules:
        rollupRules:
            ...
            storagePolicies:
              - resolution: 5m
                retention: 2160h
              - resolution: 5m
                retention: 2160h
```

In the namespace metrics_5m_90d, the metrics are written successfully, in the default:
`"msg":"could not write ingest op","error":"no configured cluster namespace for: retention=744h0m0s, resolution=10s","retryableError":true`

m3db default namespace:
```
        ...
        "aggregationOptions": {
          "aggregations": [
            {
              "aggregated": false,
              "attributes": null
            },
            {
              "aggregated": true,
              "attributes": {
                "resolutionNanos": "10000000000",
                "downsampleOptions": {
                  "all": false
                }
              }
            }
          ]
        },
        ...
```
