### ISSUE TITLE
[carbon ingester]no rules matched carbon metric, skipping", "name":"foo.bar.baz" 

### ISSUE THREAD

**Issue by cjagus** [m3db/m3#4091]
## General Issues

We are evaluating m3db as a replacemnt for Graphite datasource and followed the single node installation 
https://m3db.io/docs/quickstart/binaries/
https://m3db.io/docs/integrations/graphite/

But when I try to send a metric via command line, noticing below error 

```echo "foo.bar.baz 123 `date +%s`" | nc -N localhost 7204```

```
{"level":"debug","ts":1648503198.489223,"msg":"handling new carbon ingestion connection"}
{"level":"debug","ts":1648503198.4895532,"msg":"no rules matched carbon metric, skipping","name":"foo.bar.baz"}
{"level":"debug","ts":1648503198.4896579,"msg":"waiting for outstanding carbon ingestion writes to complete"}
{"level":"debug","ts":1648503198.489686,"msg":"all outstanding writes completed, shutting down carbon ingestion handler"}
```
Looks like metrics are getting rejected and not able to Query via API/Grafana

Config:
```
coordinator:
  logging:
    level: debug
  carbon:
    ingester:
      listenAddress: "0.0.0.0:7204"
      rules:
        - pattern: .*
          aggregation:
            type: mean
          policies:
            - resolution: 1m
              retention: 48h
db: {}
```

Is this expected behaviour or any config missing?
