### ISSUE TITLE
m3dbnode -- Allow for static topology peer list to be specified with CLI flags

### ISSUE THREAD

**Issue by nerd0** [m3db/m3#670]
To configure a static topology requires a [list of hosts/peers](https://github.com/m3db/m3db/blob/master/src/dbnode/config/m3dbnode.yml#L182-L189) 

```
            hosts:
                - hostID: m3dbnode01
                  listenAddress: "<ip_address1>:9000"
                - hostID: m3dbnode02
                  listenAddress: "<ip_address2>:9000"
                - hostID: m3dbnode03
                  listenAddress: "<ip_address3>:9000"
```

This requires developers why want to evaluate a multi-node cluster to ensure that three different YAML files are configured identically as well as reference the appropriate YAML file for each corresponding instance. 

To alleviate this overhead perhaps the compile binary could accept another flag, `peerList`. This flag could be a simple comma separated list of peers to include within the multi-node cluster. 

```
m3dbnode -f config.yaml -p <ip_address1>:9000,<ip_address2>:9000,<ip_address3>:9000
```

One potential problem with enabling this feature could lead to suboptimal techniques of creating larger multi-node clusters. That is developers might not pursue the dynamic topology feature which is backed by `etcd`.
