### ISSUE TITLE
Downsampling Non Functional v0.4.5

### ISSUE THREAD

**Issue by jacob-scheatzle** [m3db/m3#931]
Go Runtime version: go1.10.2
Build Version:      v0.4.5
Build Revision:     eef049ac
Build Branch:       master
Build Date:         2018-09-24-23:58:17

**Expected Behavior:**
M3Coordinator (used as a side car) would automatically downsample and write metrics when config specifying "aggregated" and "resolution" is picked up.

**Actual Behavior:**
M3Coordinator acknowledges the aggregated namespace but does not write anything to it. M3DB writes to unaggregated namespace as expected. No errors regarding aggregation have been observed in the log. 

**Log Snippet:**
```
2018-09-21T16:09:32.704-0400        INFO        resolved cluster namespace        {"namespace": "lowtime"}
2018-09-21T16:09:32.704-0400        INFO        resolved cluster namespace        {"namespace": "timetest"}
2018-09-21T16:09:32.708-0400        INFO        configuring downsampler to use with aggregated cluster namespaces        {"numAggregatedClusterNamespaces": 1}
```

**Layout:** 
Currently as a test setup M3DB is on 5 nodes. Each is a seed. 
The Sidecar M3Coordinator is on 2 nodes writing to M3DB and 1 node for reading. 

**M3Coordinator Config (sidecar)**
```
listenAddress:
  type: "config"
  value: "0.0.0.0:7201"

metrics:
  scope:
    prefix: "coordinator"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
  sanitization: prometheus
  samplingRate: 1.0
  extended: none

clusters:
   - namespaces:
       - namespace: timetest
         retention: 400h
         storageMetricsType: aggregated
         resolution: 2m
       - namespace: lowtime
         retention: 12h
         storageMetricsType: unaggregated
     client:
       config:
         service:
           env: default_env
           zone: embedded
           service: m3db
           cacheDir: /var/lib/m3kv
           etcdClusters:
             - zone: embedded
               endpoints:
# We have five M3DB nodes they are listed here.
                 - <removed>
                 - <removed>
                 - <removed>
                 - <removed>
                 - <removed>
       writeConsistencyLevel: majority
       readConsistencyLevel: unstrict_majority
       writeTimeout: 20s
       fetchTimeout: 25s
       connectTimeout: 20s
       writeRetry:
         initialBackoff: 500ms
         backoffFactor: 3
         maxRetries: 2
         jitter: true
       fetchRetry:
         initialBackoff: 500ms
         backoffFactor: 2
         maxRetries: 3
         jitter: true
       backgroundHealthCheckFailLimit: 4
       backgroundHealthCheckFailThrottleFactor: 0.5
```

**M3DB Config:**
```
coordinator:
  listenAddress:
    type: "config"
    value: "0.0.0.0:7201"

  metrics:
    scope:
      prefix: "coordinator"
    prometheus:
      handlerPath: /metrics
      listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
    sanitization: prometheus
    samplingRate: 1.0
    extended: none

db:
  logging:
    level: info

  metrics:
    prometheus:
      handlerPath: /metrics
    sanitization: prometheus
    samplingRate: 1.0
    extended: detailed

  hostID:
    resolver: environment
    envVarName: M3DB_HOST_ID

#Fill-out the following and un-comment before using.
  config:
    service:
      env: default_env
      zone: embedded
      service: m3db
      cacheDir: /var/lib/m3kv
      etcdClusters:
        - zone: embedded
          endpoints:
            - <removed>
            - <removed>
            - <removed>
            - <removed>
            - <removed>

    seedNodes:
      initialCluster:
        - hostID: m3db1
          endpoint: <removed>
        - hostID: m3db2
          endpoint: <removed>
        - hostID: m3db3
          endpoint: <removed>
        - hostID: m3db4
          endpoint: <removed>
        - hostID: m3db5
          endpoint: <removed>

  listenAddress: 0.0.0.0:9000
  clusterListenAddress: 0.0.0.0:9001
  httpNodeListenAddress: 0.0.0.0:9002
  httpClusterListenAddress: 0.0.0.0:9003
  debugListenAddress: 0.0.0.0:9004

  client:
    writeConsistencyLevel: majority
    readConsistencyLevel: unstrict_majority
    writeTimeout: 10s
    fetchTimeout: 15s
    connectTimeout: 20s
    writeRetry:
        initialBackoff: 500ms
        backoffFactor: 3
        maxRetries: 2
        jitter: true
    fetchRetry:
        initialBackoff: 500ms
        backoffFactor: 2
        maxRetries: 3
        jitter: true
    backgroundHealthCheckFailLimit: 4
    backgroundHealthCheckFailThrottleFactor: 0.5

  gcPercentage: 100

  writeNewSeriesAsync: true
  writeNewSeriesLimitPerSecond: 1048576
  writeNewSeriesBackoffDuration: 2ms

  bootstrap:
    bootstrappers:
        - filesystem
        - commitlog
        - peers
        - uninitialized_topology
    fs:
        numProcessorsPerCPU: 0.125

  cache:
    series:
      policy: lru

  commitlog:
    flushMaxBytes: 524288
    flushEvery: 1s
    queue:
        calculationType: fixed
        size: 2097152
    blockSize: 10m

  fs:
    filePathPrefix: /var/lib/m3db
    writeBufferSize: 65536
    dataReadBufferSize: 65536
    infoReadBufferSize: 128
    seekReadBufferSize: 4096
    throughputLimitMbps: 100.0
    throughputCheckEvery: 128

  repair:
    enabled: false
    interval: 2h
    offset: 30m
    jitter: 1h
    throttle: 2m
    checkInterval: 1m

  pooling:
    blockAllocSize: 16
    type: simple
    seriesPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    blockPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    encoderPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    closersPool:
        size: 104857
        lowWatermark: 0.7
        highWatermark: 1.0
    contextPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    segmentReaderPool:
        size: 16384
        lowWatermark: 0.7
        highWatermark: 1.0
    iteratorPool:
        size: 2048
        lowWatermark: 0.7
        highWatermark: 1.0
    fetchBlockMetadataResultsPool:
        size: 65536
        capacity: 32
        lowWatermark: 0.7
        highWatermark: 1.0
    fetchBlocksMetadataResultsPool:
        size: 32
        capacity: 4096
        lowWatermark: 0.7
        highWatermark: 1.0
    hostBlockMetadataSlicePool:
        size: 131072
        capacity: 3
        lowWatermark: 0.7
        highWatermark: 1.0
    blockMetadataPool:
        size: 65536
        lowWatermark: 0.7
        highWatermark: 1.0
    blockMetadataSlicePool:
        size: 65536
        capacity: 32
        lowWatermark: 0.7
        highWatermark: 1.0
    blocksMetadataPool:
        size: 65536
        lowWatermark: 0.7
        highWatermark: 1.0
    blocksMetadataSlicePool:
        size: 32
        capacity: 4096
        lowWatermark: 0.7
        highWatermark: 1.0
    identifierPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    bytesPool:
        buckets:
            - capacity: 16
              size: 524288
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 32
              size: 262144
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 64
              size: 131072
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 128
              size: 65536
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 256
              size: 65536
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 1440
              size: 16384
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 4096
              size: 8192
              lowWatermark: 0.7
              highWatermark: 1.0
```

**Namespace Declaration:**
```
curl -X POST localhost:7201/api/v1/namespace -d '{
  "name": "timetest",
  "options": {
    "bootstrapEnabled": true,
    "flushEnabled": true,
    "writesToCommitLog": true,
    "cleanupEnabled": true,
    "snapshotEnabled": true,
    "repairEnabled": false,
    "retentionOptions": {
      "retentionPeriodDuration": "400h",
      "blockSizeDuration": "4h",
      "bufferFutureDuration": "1h",
      "bufferPastDuration": "1h",
      "blockDataExpiry": true,
      "blockDataExpiryAfterNotAccessPeriodDuration": "5m"
    },
    "indexOptions": {
      "enabled": true,
      "blockSizeDuration": "4h"
    }
  }
}'

curl -X POST localhost:7201/api/v1/namespace -d '{
  "name": "lowtime",
  "options": {
    "bootstrapEnabled": true,
    "flushEnabled": true,
    "writesToCommitLog": true,
    "cleanupEnabled": true,
    "snapshotEnabled": true,
    "repairEnabled": false,
    "retentionOptions": {
      "retentionPeriodDuration": "12h",
      "blockSizeDuration": "4h",
      "bufferFutureDuration": "1h",
      "bufferPastDuration": "1h",
      "blockDataExpiry": true,
      "blockDataExpiryAfterNotAccessPeriodDuration": "5m"
    },
    "indexOptions": {
      "enabled": true,
      "blockSizeDuration": "4h"
    }
  }
}'
```
